### ISSUE TITLE
make vfs

### ISSUE THREAD

**Issue by ghost** [hexahedronic/luahexed#2]
~~We're~~ I'm going to die in a fire if vfs is not made.

**Comment by CaveeJohnson** [comment]
you_, not we_

**Comment by ghost** [comment]
thanks for noticing, fixed

**Comment by CaveeJohnson** [comment]
i guess he died in a fire because we still dont have a vfs

**Comment by ghost** [comment]
IT'S FUCKING DONE NOW: db16ff7
